/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class main_MainGUI */

#ifndef _Included_main_MainGUI
#define _Included_main_MainGUI
#ifdef __cplusplus
extern "C" {
#endif
#undef main_MainGUI_FOCUS_TRAVERSABLE_UNKNOWN
#define main_MainGUI_FOCUS_TRAVERSABLE_UNKNOWN 0L
#undef main_MainGUI_FOCUS_TRAVERSABLE_DEFAULT
#define main_MainGUI_FOCUS_TRAVERSABLE_DEFAULT 1L
#undef main_MainGUI_FOCUS_TRAVERSABLE_SET
#define main_MainGUI_FOCUS_TRAVERSABLE_SET 2L
#undef main_MainGUI_TOP_ALIGNMENT
#define main_MainGUI_TOP_ALIGNMENT 0.0f
#undef main_MainGUI_CENTER_ALIGNMENT
#define main_MainGUI_CENTER_ALIGNMENT 0.5f
#undef main_MainGUI_BOTTOM_ALIGNMENT
#define main_MainGUI_BOTTOM_ALIGNMENT 1.0f
#undef main_MainGUI_LEFT_ALIGNMENT
#define main_MainGUI_LEFT_ALIGNMENT 0.0f
#undef main_MainGUI_RIGHT_ALIGNMENT
#define main_MainGUI_RIGHT_ALIGNMENT 1.0f
#undef main_MainGUI_serialVersionUID
#define main_MainGUI_serialVersionUID -7644114512714619750LL
#undef main_MainGUI_serialVersionUID
#define main_MainGUI_serialVersionUID 4613797578919906343LL
#undef main_MainGUI_INCLUDE_SELF
#define main_MainGUI_INCLUDE_SELF 1L
#undef main_MainGUI_SEARCH_HEAVYWEIGHTS
#define main_MainGUI_SEARCH_HEAVYWEIGHTS 1L
#undef main_MainGUI_OPENED
#define main_MainGUI_OPENED 1L
#undef main_MainGUI_serialVersionUID
#define main_MainGUI_serialVersionUID 4497834738069338734LL
#undef main_MainGUI_DEFAULT_CURSOR
#define main_MainGUI_DEFAULT_CURSOR 0L
#undef main_MainGUI_CROSSHAIR_CURSOR
#define main_MainGUI_CROSSHAIR_CURSOR 1L
#undef main_MainGUI_TEXT_CURSOR
#define main_MainGUI_TEXT_CURSOR 2L
#undef main_MainGUI_WAIT_CURSOR
#define main_MainGUI_WAIT_CURSOR 3L
#undef main_MainGUI_SW_RESIZE_CURSOR
#define main_MainGUI_SW_RESIZE_CURSOR 4L
#undef main_MainGUI_SE_RESIZE_CURSOR
#define main_MainGUI_SE_RESIZE_CURSOR 5L
#undef main_MainGUI_NW_RESIZE_CURSOR
#define main_MainGUI_NW_RESIZE_CURSOR 6L
#undef main_MainGUI_NE_RESIZE_CURSOR
#define main_MainGUI_NE_RESIZE_CURSOR 7L
#undef main_MainGUI_N_RESIZE_CURSOR
#define main_MainGUI_N_RESIZE_CURSOR 8L
#undef main_MainGUI_S_RESIZE_CURSOR
#define main_MainGUI_S_RESIZE_CURSOR 9L
#undef main_MainGUI_W_RESIZE_CURSOR
#define main_MainGUI_W_RESIZE_CURSOR 10L
#undef main_MainGUI_E_RESIZE_CURSOR
#define main_MainGUI_E_RESIZE_CURSOR 11L
#undef main_MainGUI_HAND_CURSOR
#define main_MainGUI_HAND_CURSOR 12L
#undef main_MainGUI_MOVE_CURSOR
#define main_MainGUI_MOVE_CURSOR 13L
#undef main_MainGUI_NORMAL
#define main_MainGUI_NORMAL 0L
#undef main_MainGUI_ICONIFIED
#define main_MainGUI_ICONIFIED 1L
#undef main_MainGUI_MAXIMIZED_HORIZ
#define main_MainGUI_MAXIMIZED_HORIZ 2L
#undef main_MainGUI_MAXIMIZED_VERT
#define main_MainGUI_MAXIMIZED_VERT 4L
#undef main_MainGUI_MAXIMIZED_BOTH
#define main_MainGUI_MAXIMIZED_BOTH 6L
#undef main_MainGUI_serialVersionUID
#define main_MainGUI_serialVersionUID 2673458971256075116LL
#undef main_MainGUI_EXIT_ON_CLOSE
#define main_MainGUI_EXIT_ON_CLOSE 3L
#undef main_MainGUI_MIDASINPUT
#define main_MainGUI_MIDASINPUT 0L
#undef main_MainGUI_LINEGRAPH
#define main_MainGUI_LINEGRAPH 1L
#undef main_MainGUI_DOTPLOT
#define main_MainGUI_DOTPLOT 2L
#undef main_MainGUI_HISTOGRAM
#define main_MainGUI_HISTOGRAM 3L
#ifdef __cplusplus
}
#endif
#endif
